export const quizData = [
    { image: require('../../assets/images/signTestImg/stopLookGo.png'), correctAnswer: 'Stop and Look Before Going', options: ['Stop and Look Before Going', 'Go Straight', 'Turn Right'] },
    { image: require('../../assets/images/signTestImg/vechileWidthLimit.png'), correctAnswer: 'Vehicle Width Limit', options: ['Vehicle Width Limit', 'No Entry', 'Speed Limit'] },
    { image: require('../../assets/images/signTestImg/vechileWeightLimit.png'), correctAnswer: 'Vehicle Weight Limit', options: ['Vehicle Weight Limit', 'Height Limit', 'Speed Limit'] },
    { image: require('../../assets/images/signTestImg/twoWayRoadStraightAhead.png'), correctAnswer: 'Two Way Road Straight Ahead', options: ['Two Way Road Straight Ahead', 'One Way Road', 'T Junction'] },
    { image: require('../../assets/images/signTestImg/turnLeftByGoingAhead.png'), correctAnswer: 'Turn Left By Going Ahead', options: ['Turn Left By Going Ahead', 'Turn Right', 'Go Straight'] },
    { image: require('../../assets/images/signTestImg/traffic.png'), correctAnswer: 'Traffic Signal Ahead', options: ['Traffic Signal Ahead', 'School Zone', 'Hospital'] },
    { image: require('../../assets/images/signTestImg/schoolZone.png'), correctAnswer: 'School Zone', options: ['School Zone', 'Hospital Zone', 'Parking Zone'] },
    { image: require('../../assets/images/signTestImg/rockFallingPlaace.png'), correctAnswer: 'Rock Falling Place', options: ['Rock Falling Place', 'Dangerous Area', 'Construction Zone'] },
    { image: require('../../assets/images/signTestImg/noOvertake.png'), correctAnswer: 'No Overtaking', options: ['No Overtaking', 'Speed Limit', 'No Entry'] },
    { image: require('../../assets/images/signTestImg/noEntry.png'), correctAnswer: 'No Entry', options: ['No Entry', 'Stop', 'Give Way'] },
    { image: require('../../assets/images/signTestImg/narrowRoad.png'), correctAnswer: 'Narrow Road', options: ['Narrow Road', 'Wide Road', 'Bridge Ahead'] },
    { image: require('../../assets/images/signTestImg/goFromAnyway.png'), correctAnswer: 'Go From Anyway', options: ['Go From Anyway', 'Stop', 'Wait'] },
    { image: require('../../assets/images/signTestImg/frontHeightLimit.png'), correctAnswer: 'Front Height Limit', options: ['Front Height Limit', 'Weight Limit', 'Speed Limit'] },
    { image: require('../../assets/images/signTestImg/dualTurningFirstLeft.png'), correctAnswer: 'Dual Turning First Left', options: ['Dual Turning First Left', 'Turn Right', 'Go Straight'] },
    { image: require('../../assets/images/signTestImg/dangerous.png'), correctAnswer: 'Dangerous Area', options: ['Dangerous Area', 'Safe Zone', 'Construction Zone'] },
    { image: require('../../assets/images/signTestImg/vechileHeightLimit.png'), correctAnswer: 'Vehicle Height Limit', options: ['Vehicle Height Limit', 'Weight Limit', 'Width Limit'] },
    { image: require('../../assets/images/signTestImg/upwardWayOfHill.png'), correctAnswer: 'Upward Way of Hill', options: ['Upward Way of Hill', 'Downhill', 'Level Road'] },
    { image: require('../../assets/images/signTestImg/twoWayRoadAhead.png'), correctAnswer: 'Two Way Road Ahead', options: ['Two Way Road Ahead', 'One Way Road', 'Dead End'] },
    { image: require('../../assets/images/signTestImg/turnRight.png'), correctAnswer: 'Turn Right', options: ['Turn Right', 'Turn Left', 'Go Straight'] },
    { image: require('../../assets/images/signTestImg/turnFullRight.png'), correctAnswer: 'Turn Full Right', options: ['Turn Full Right', 'Turn Left', 'U Turn'] },
    { image: require('../../assets/images/signTestImg/tJunction.png'), correctAnswer: 'T Junction', options: ['T Junction', 'Y Junction', 'Cross Road'] },
    { image: require('../../assets/images/signTestImg/takeToLeftSide.png'), correctAnswer: 'Take To Left Side', options: ['Take To Left Side', 'Take To Right Side', 'Stay In Center'] },
    { image: require('../../assets/images/signTestImg/riverSide.png'), correctAnswer: 'River Side', options: ['River Side', 'Bridge Ahead', 'Water Crossing'] },
    { image: require('../../assets/images/signTestImg/noUturn.png'), correctAnswer: 'No U Turn', options: ['No U Turn', 'U Turn Allowed', 'Turn Left'] },
    { image: require('../../assets/images/signTestImg/noTruck.png'), correctAnswer: 'No Truck', options: ['No Truck', 'Truck Zone', 'Heavy Vehicle'] },
    { image: require('../../assets/images/signTestImg/noStoppage.png'), correctAnswer: 'No Stoppage', options: ['No Stoppage', 'Parking Allowed', 'Stop Here'] },
    { image: require('../../assets/images/signTestImg/noRightTurn.png'), correctAnswer: 'No Right Turn', options: ['No Right Turn', 'Turn Right', 'Go Straight'] },
    { image: require('../../assets/images/signTestImg/noParking.png'), correctAnswer: 'No Parking', options: ['No Parking', 'Parking Allowed', 'Loading Zone'] },
    { image: require('../../assets/images/signTestImg/noLeftTurn.png'), correctAnswer: 'No Left Turn', options: ['No Left Turn', 'Turn Left', 'Go Straight'] },
    { image: require('../../assets/images/signTestImg/noHorn.png'), correctAnswer: 'No Horn', options: ['No Horn', 'Horn Allowed', 'Quiet Zone'] },
    { image: require('../../assets/images/signTestImg/maxSpeedLimit.png'), correctAnswer: 'Maximum Speed Limit', options: ['Maximum Speed Limit', 'Minimum Speed', 'Speed Zone'] },
    { image: require('../../assets/images/signTestImg/GoTempporary.png'), correctAnswer: 'Go Temporary', options: ['Go Temporary', 'Stop', 'Wait'] },
    { image: require('../../assets/images/signTestImg/goStraightOnly.png'), correctAnswer: 'Go Straight Only', options: ['Go Straight Only', 'Turn Left', 'Turn Right'] },
    { image: require('../../assets/images/signTestImg/dangerousDipRoad.png'), correctAnswer: 'Dangerous Dip Road', options: ['Dangerous Dip Road', 'Bumpy Road', 'Smooth Road'] },
    { image: require('../../assets/images/signTestImg/circularRoad.png'), correctAnswer: 'Circular Road', options: ['Circular Road', 'Straight Road', 'Curved Road'] },
    { image: require('../../assets/images/signTestImg/turnLeft.png'), correctAnswer: 'Turn Left', options: ['Turn Left', 'Turn Right', 'Go Straight'] },
    { image: require('../../assets/images/signTestImg/speedLimitEnd.png'), correctAnswer: 'Speed Limit End', options: ['Speed Limit End', 'Speed Zone', 'Speed Limit'] },
    { image: require('../../assets/images/signTestImg/SharpTurn(TemporaryPath).png'), correctAnswer: 'Sharp Turn Temporary Path', options: ['Sharp Turn Temporary Path', 'Curved Road', 'Straight Road'] },
    { image: require('../../assets/images/signTestImg/narrowBridge.png'), correctAnswer: 'Narrow Bridge', options: ['Narrow Bridge', 'Wide Bridge', 'Tunnel'] },
    { image: require('../../assets/images/signTestImg/naarrowRoadRightSide.png'), correctAnswer: 'Narrow Road Right Side', options: ['Narrow Road Right Side', 'Wide Road', 'One Way'] },
    { image: require('../../assets/images/signTestImg/mainRoadBeforeCrossroad.png'), correctAnswer: 'Main Road Before Crossroad', options: ['Main Road Before Crossroad', 'Side Road', 'Highway'] },
    { image: require('../../assets/images/signTestImg/tJunction(RightLeftTurn).png'), correctAnswer: 'T Junction Right Left Turn', options: ['T Junction Right Left Turn', 'Y Junction', 'Cross Road'] },
    { image: require('../../assets/images/signTestImg/sharpTurnToLeft.png'), correctAnswer: 'Sharp Turn To Left', options: ['Sharp Turn To Left', 'Curved Road', 'Straight Road'] },
    { image: require('../../assets/images/signTestImg/vechileMayComeLefttSide.png'), correctAnswer: 'Vehicle May Come Left Side', options: ['Vehicle May Come Left Side', 'Right Side', 'Center'] },
    { image: require('../../assets/images/signTestImg/vechileMayComeRightSide.png'), correctAnswer: 'Vehicle May Come Right Side', options: ['Vehicle May Come Right Side', 'Left Side', 'Center'] },
    { image: require('../../assets/images/signTestImg/yJunction.png'), correctAnswer: 'Y Junction', options: ['Y Junction', 'T Junction', 'Cross Road'] },
    { image: require('../../assets/images/signTestImg/noOxenCart.png'), correctAnswer: 'No Oxen Cart', options: ['No Oxen Cart', 'Animal Crossing', 'Farm Zone'] },
    { image: require('../../assets/images/signTestImg/vechileLimitLength.png'), correctAnswer: 'Vehicle Limit Length', options: ['Vehicle Limit Length', 'Height Limit', 'Weight Limit'] },
    { image: require('../../assets/images/signTestImg/stopAndGo.png'), correctAnswer: 'Stop And Go', options: ['Stop And Go', 'Stop', 'Go'] },
    { image: require('../../assets/images/signTestImg/oneWayTraffic.png'), correctAnswer: 'One Way Traffic', options: ['One Way Traffic', 'Two Way', 'No Entry'] },
];

export const quizEyeTest = [
    { image: require('../../assets/images/eyeTestImg/74.png'), correctAnswer: '74', options: ['71', '74', '79'] },
    { image: require('../../assets/images/eyeTestImg/5.png'), correctAnswer: '5', options: ['2', '5', '6'] },
    { image: require('../../assets/images/eyeTestImg/42.png'), correctAnswer: '42', options: ['45', '42', '48'] },
    { image: require('../../assets/images/eyeTestImg/16.png'), correctAnswer: '16', options: ['16', '19', '18'] },
    { image: require('../../assets/images/eyeTestImg/97.png'), correctAnswer: '97', options: ['97', '91', '79'] },
    { image: require('../../assets/images/eyeTestImg/8.png'), correctAnswer: '8', options: ['8', '3', '6'] },
    { image: require('../../assets/images/eyeTestImg/29.png'), correctAnswer: '29', options: ['29', '26', '28'] },
    { image: require('../../assets/images/eyeTestImg/3.png'), correctAnswer: '3', options: ['3', '8', '5'] },
    { image: require('../../assets/images/eyeTestImg/73.png'), correctAnswer: '73', options: ['73', '78', '75'] },
    { image: require('../../assets/images/eyeTestImg/12.png'), correctAnswer: '12', options: ['12', '13', '15'] },
    { image: require('../../assets/images/eyeTestImg/96.png'), correctAnswer: '96', options: ['96', '99', '86'] },
    { image: require('../../assets/images/eyeTestImg/7.png'), correctAnswer: '7', options: ['1', '7', '9'] },
    { image: require('../../assets/images/eyeTestImg/45.png'), correctAnswer: '45', options: ['45', '43', '48'] },
    { image: require('../../assets/images/eyeTestImg/2.png'), correctAnswer: '2', options: ['4', '2', '1'] },
    { image: require('../../assets/images/eyeTestImg/35.png'), correctAnswer: '35', options: ['35', '38', '33'] },
    { image: require('../../assets/images/eyeTestImg/9.png'), correctAnswer: '9', options: ['6', '9', '4'] },
    { image: require('../../assets/images/eyeTestImg/27.png'), correctAnswer: '27', options: ['21', '27', '29'] },
    { image: require('../../assets/images/eyeTestImg/6.png'), correctAnswer: '6', options: ['6', '9', '8'] },
    { image: require('../../assets/images/eyeTestImg/15.png'), correctAnswer: '15', options: ['16', '15', '18'] },
    { image: require('../../assets/images/eyeTestImg/26.png'), correctAnswer: '26', options: ['26', '25', '28'] },
];
