export const informativeSign: { key: string; label: string; src: any }[] = [
    { key: 'traffic', label: 'Traffic', src: require('../../assets/images/informativeSign/traffic.png') },
    { key: 'turnFullRight', label: 'Full Right Turn', src: require('../../assets/images/informativeSign/turnFullRight.png') },
    { key: 'turnLeft', label: 'Turn Left', src: require('../../assets/images/informativeSign/turnLeft.png') },
    { key: 'turnLeftByGoingAhead', label: 'Turn Left By Going Ahead', src: require('../../assets/images/informativeSign/turnLeftByGoingAhead.png') },
    { key: 'goStraightOnly', label: 'Go Straight Only', src: require('../../assets/images/informativeSign/goStraightOnly.png') },
    { key: 'goFromAnyway', label: 'Go From Any Way', src: require('../../assets/images/informativeSign/goFromAnyway.png') },
    { key: 'GoTempporary', label: 'Go Temporary', src: require('../../assets/images/informativeSign/GoTempporary.png') },
    { key: 'dualTurningFirstLeft', label: 'Dual Turning First Left', src: require('../../assets/images/informativeSign/dualTurningFirstLeft.png') },
    { key: 'oneWayTraffic', label: 'One Way Traffic', src: require('../../assets/images/informativeSign/oneWayTraffic.png') },
    { key: 'twoWayRoadAhead', label: 'Two Way Road Ahead', src: require('../../assets/images/informativeSign/twoWayRoadAhead.png') },
    { key: 'twoWayRoadStraightAhead', label: 'Two Way Road Straight Ahead', src: require('../../assets/images/informativeSign/twoWayRoadStraightAhead.png') },
    { key: 'mainRoadBeforeCrossroad', label: 'Main Road Before Crossroad', src: require('../../assets/images/informativeSign/mainRoadBeforeCrossroad.png') },
    { key: 'circularRoad', label: 'Circular Road', src: require('../../assets/images/informativeSign/circularRoad.png') },
    { key: 'tJunction', label: 'T-Junction', src: require('../../assets/images/informativeSign/tJunction.png') },
    { key: 'tJunctionRL', label: 'T-Junction (Right/Left Turn)', src: require('../../assets/images/informativeSign/tJunction(RightLeftTurn).png') },
    { key: 'yJunction', label: 'Y-Junction', src: require('../../assets/images/informativeSign/yJunction.png') },
    { key: 'narrowRoad', label: 'Narrow Road', src: require('../../assets/images/informativeSign/narrowRoad.png') },
    { key: 'narrowBridge', label: 'Narrow Bridge', src: require('../../assets/images/informativeSign/narrowBridge.png') },
    { key: 'naarrowRoadRightSide', label: 'Narrow Road Right Side', src: require('../../assets/images/informativeSign/naarrowRoadRightSide.png') },
    { key: 'riverSide', label: 'River Side', src: require('../../assets/images/informativeSign/riverSide.png') },
    { key: 'rockFallingPlaace', label: 'Rock Falling Place', src: require('../../assets/images/informativeSign/rockFallingPlaace.png') },
    { key: 'upwardWayOfHill', label: 'Upward Way Of Hill', src: require('../../assets/images/informativeSign/upwardWayOfHill.png') },
    { key: 'schoolZone', label: 'School Zone', src: require('../../assets/images/informativeSign/schoolZone.png') },
    { key: 'dangerous', label: 'Dangerous', src: require('../../assets/images/informativeSign/dangerous.png') },
    { key: 'dangerousDipRoad', label: 'Dangerous Dip Road', src: require('../../assets/images/informativeSign/dangerousDipRoad.png') },
    { key: 'sharpTurnToLeft', label: 'Sharp Turn To Left', src: require('../../assets/images/informativeSign/sharpTurnToLeft.png') },
    { key: 'sharpTurnTemporary', label: 'Sharp Turn (Temporary Path)', src: require('../../assets/images/informativeSign/SharpTurn(TemporaryPath).png') },
    { key: 'stopLookGo', label: 'Stop Look Go', src: require('../../assets/images/informativeSign/stopLookGo.png') },
    { key: 'stopAndGo', label: 'Stop And Go', src: require('../../assets/images/informativeSign/stopAndGo.png') },
    { key: 'takeToLeftSide', label: 'Take To Left Side', src: require('../../assets/images/informativeSign/takeToLeftSide.png') },
    { key: 'maxSpeedLimit', label: 'Max Speed Limit', src: require('../../assets/images/informativeSign/maxSpeedLimit.png') },
    { key: 'frontHeightLimit', label: 'Vehicle Height Limit', src: require('../../assets/images/informativeSign/frontHeightLimit.png') },
    { key: 'vechileHeightLimit', label: 'Vehicle Height Limit', src: require('../../assets/images/informativeSign/vechileHeightLimit.png') },
    { key: 'vechileLimitLength', label: 'Vehicle Limit Length', src: require('../../assets/images/informativeSign/vechileLimitLength.png') },
    { key: 'vechileWeightLimit', label: 'Vehicle Weight Limit', src: require('../../assets/images/informativeSign/vechileWeightLimit.png') },
    { key: 'vechileWidthLimit', label: 'Vehicle Width Limit', src: require('../../assets/images/informativeSign/vechileWidthLimit.png') },
    { key: 'vechileMayComeLefttSide', label: 'Vehicle May Come Left Side', src: require('../../assets/images/informativeSign/vechileMayComeLefttSide.png') },
    { key: 'vechileMayComeRightSide', label: 'Vehicle May Come Right Side', src: require('../../assets/images/informativeSign/vechileMayComeRightSide.png') },
    { key: 'noEntry', label: 'No Entry', src: require('../../assets/images/informativeSign/noEntry.png') },
  ];

export const restrictiveSign: { key: string; label: string; src: any }[] = [
  { key: 'noHorn', label: 'No Horn', src: require('../../assets/images/restrictiveSign/noHorn.png') },
  { key: 'noLeftTurn', label: 'No Left Turn', src: require('../../assets/images/restrictiveSign/noLeftTurn.png') },
  { key: 'noOvertake', label: 'No Overtake', src: require('../../assets/images/restrictiveSign/noOvertake.png') },
  { key: 'noOxenCart', label: 'No Oxen Cart', src: require('../../assets/images/restrictiveSign/noOxenCart.png') },
  { key: 'noParking', label: 'No Parking', src: require('../../assets/images/restrictiveSign/noParking.png') },
  { key: 'noRightTurn', label: 'No Right Turn', src: require('../../assets/images/restrictiveSign/noRightTurn.png') },
  { key: 'noStoppage', label: 'No Stoppage', src: require('../../assets/images/restrictiveSign/noStoppage.png') },
  { key: 'noTruck', label: 'No Truck', src: require('../../assets/images/restrictiveSign/noTruck.png') },
  { key: 'noUturn', label: 'No U Turn', src: require('../../assets/images/restrictiveSign/noUturn.png') },
  { key: 'speedLimitEnd', label: 'Speed Limit End', src: require('../../assets/images/restrictiveSign/speedLimitEnd.png') },
  { key: 'turnRight', label: 'Turn Right', src: require('../../assets/images/restrictiveSign/turnRight.png') },
];

export const numberSign: { key: string; label: string; src: any }[] = [
  { key: '2', label: '2', src: require('../../assets/images/eyeTestImg/2.png') },
  { key: '3', label: '3', src: require('../../assets/images/eyeTestImg/3.png') },
  { key: '5', label: '5', src: require('../../assets/images/eyeTestImg/5.png') },
  { key: '6', label: '6', src: require('../../assets/images/eyeTestImg/6.png') },
  { key: '7', label: '7', src: require('../../assets/images/eyeTestImg/7.png') },
  { key: '8', label: '8', src: require('../../assets/images/eyeTestImg/8.png') },
  { key: '9', label: '9', src: require('../../assets/images/eyeTestImg/9.png') },
  { key: '12', label: '12', src: require('../../assets/images/eyeTestImg/12.png') },
  { key: '15', label: '15', src: require('../../assets/images/eyeTestImg/15.png') },
  { key: '16', label: '16', src: require('../../assets/images/eyeTestImg/16.png') },
  { key: '26', label: '26', src: require('../../assets/images/eyeTestImg/26.png') },
  { key: '27', label: '27', src: require('../../assets/images/eyeTestImg/27.png') },
  { key: '29', label: '29', src: require('../../assets/images/eyeTestImg/29.png') },
  { key: '35', label: '35', src: require('../../assets/images/eyeTestImg/35.png') },
  { key: '42', label: '42', src: require('../../assets/images/eyeTestImg/42.png') },
  { key: '45', label: '45', src: require('../../assets/images/eyeTestImg/45.png') },
  { key: '73', label: '73', src: require('../../assets/images/eyeTestImg/73.png') },
  { key: '74', label: '74', src: require('../../assets/images/eyeTestImg/74.png') },
  { key: '96', label: '96', src: require('../../assets/images/eyeTestImg/96.png') },
  { key: '97', label: '97', src: require('../../assets/images/eyeTestImg/97.png') },
];
