export const informativeSign: { key: string; label: string; labelNp: string; src: any }[] = [
    { key: 'traffic', label: 'Traffic', labelNp: 'ट्राफिक सङ्केत', src: require('../../assets/images/informativeSign/traffic.png') },
    { key: 'turnFullRight', label: 'Full Right Turn', labelNp: 'दायाँ मोड्नुहोस्', src: require('../../assets/images/informativeSign/turnFullRight.png') },
    { key: 'turnLeft', label: 'Turn Left', labelNp: 'बायाँ मोड्नुहोस्', src: require('../../assets/images/informativeSign/turnLeft.png') },
    { key: 'turnLeftByGoingAhead', label: 'Turn Left By Going Ahead', labelNp: 'अगाडि बढेर बायाँ मोड्नुहोस्', src: require('../../assets/images/informativeSign/turnLeftByGoingAhead.png') },
    { key: 'goStraightOnly', label: 'Go Straight Only', labelNp: 'सीधा मात्र जानुहोस्', src: require('../../assets/images/informativeSign/goStraightOnly.png') },
    { key: 'goFromAnyway', label: 'Go From Any Way', labelNp: 'जुनसुकै तर्फबाट जानुहोस्', src: require('../../assets/images/informativeSign/goFromAnyway.png') },
    { key: 'GoTempporary', label: 'Go Temporary', labelNp: 'अस्थायी बाटो प्रयोग गर्नुहोस्', src: require('../../assets/images/informativeSign/GoTempporary.png') },
    { key: 'dualTurningFirstLeft', label: 'Dual Turning First Left', labelNp: 'दोहोरो मोड (पहिलो बायाँ)', src: require('../../assets/images/informativeSign/dualTurningFirstLeft.png') },
    { key: 'oneWayTraffic', label: 'One Way Traffic', labelNp: 'एकतर्फी यातायात', src: require('../../assets/images/informativeSign/oneWayTraffic.png') },
    { key: 'twoWayRoadAhead', label: 'Two Way Road Ahead', labelNp: 'अगाडि दोहोरो सडक', src: require('../../assets/images/informativeSign/twoWayRoadAhead.png') },
    { key: 'twoWayRoadStraightAhead', label: 'Two Way Road Straight Ahead', labelNp: 'अगाडि सीधा दोहोरो सडक', src: require('../../assets/images/informativeSign/twoWayRoadStraightAhead.png') },
    { key: 'mainRoadBeforeCrossroad', label: 'Main Road Before Crossroad', labelNp: 'चौबाटो अगाडि मुख्य सडक', src: require('../../assets/images/informativeSign/mainRoadBeforeCrossroad.png') },
    { key: 'circularRoad', label: 'Circular Road', labelNp: 'गोलघुम्ती', src: require('../../assets/images/informativeSign/circularRoad.png') },
    { key: 'tJunction', label: 'T-Junction', labelNp: 'टी-मोड (T-जक्सन)', src: require('../../assets/images/informativeSign/tJunction.png') },
    { key: 'tJunctionRL', label: 'T-Junction (Right/Left Turn)', labelNp: 'टी-मोड (दायाँ/बायाँ मोड्नुहोस्)', src: require('../../assets/images/informativeSign/tJunction(RightLeftTurn).png') },
    { key: 'yJunction', label: 'Y-Junction', labelNp: 'वाई-मोड (Y-जक्सन)', src: require('../../assets/images/informativeSign/yJunction.png') },
    { key: 'narrowRoad', label: 'Narrow Road', labelNp: 'साँघुरो सडक', src: require('../../assets/images/informativeSign/narrowRoad.png') },
    { key: 'narrowBridge', label: 'Narrow Bridge', labelNp: 'साँघुरो पुल', src: require('../../assets/images/informativeSign/narrowBridge.png') },
    { key: 'naarrowRoadRightSide', label: 'Narrow Road Right Side', labelNp: 'दायाँतर्फ साँघुरो सडक', src: require('../../assets/images/informativeSign/naarrowRoadRightSide.png') },
    { key: 'riverSide', label: 'River Side', labelNp: 'नदी किनाराको सडक', src: require('../../assets/images/informativeSign/riverSide.png') },
    { key: 'rockFallingPlaace', label: 'Rock Falling Place', labelNp: 'ढुङ्गा झर्ने / पहिरो जाने क्षेत्र', src: require('../../assets/images/informativeSign/rockFallingPlaace.png') },
    { key: 'upwardWayOfHill', label: 'Upward Way Of Hill', labelNp: 'उकालो सडक', src: require('../../assets/images/informativeSign/upwardWayOfHill.png') },
    { key: 'schoolZone', label: 'School Zone', labelNp: 'विद्यालय क्षेत्र', src: require('../../assets/images/informativeSign/schoolZone.png') },
    { key: 'dangerous', label: 'Dangerous', labelNp: 'खतरनाक मोड/क्षेत्र', src: require('../../assets/images/informativeSign/dangerous.png') },
    { key: 'dangerousDipRoad', label: 'Dangerous Dip Road', labelNp: 'खतरनाक होचो सडक (गहिरो सडक)', src: require('../../assets/images/informativeSign/dangerousDipRoad.png') },
    { key: 'sharpTurnToLeft', label: 'Sharp Turn To Left', labelNp: 'तीव्र बायाँ मोड', src: require('../../assets/images/informativeSign/sharpTurnToLeft.png') },
    { key: 'sharpTurnTemporary', label: 'Sharp Turn (Temporary Path)', labelNp: 'अस्थायी तीव्र मोड', src: require('../../assets/images/informativeSign/SharpTurn(TemporaryPath).png') },
    { key: 'stopLookGo', label: 'Stop Look Go', labelNp: 'रोक, हेर र जाऊ', src: require('../../assets/images/informativeSign/stopLookGo.png') },
    { key: 'stopAndGo', label: 'Stop And Go', labelNp: 'रोकिँदै र जाँदै गर्नुहोस्', src: require('../../assets/images/informativeSign/stopAndGo.png') },
    { key: 'takeToLeftSide', label: 'Take To Left Side', labelNp: 'बायाँ च्यापेर चलाउनुहोस्', src: require('../../assets/images/informativeSign/takeToLeftSide.png') },
    { key: 'maxSpeedLimit', label: 'Max Speed Limit', labelNp: 'अधिकतम गति सीमा', src: require('../../assets/images/informativeSign/maxSpeedLimit.png') },
    { key: 'frontHeightLimit', label: 'Vehicle Height Limit', labelNp: 'सवारी साधनको उचाइ सीमा', src: require('../../assets/images/informativeSign/frontHeightLimit.png') },
    { key: 'vechileHeightLimit', label: 'Vehicle Height Limit', labelNp: 'सवारी उचाइ सीमा', src: require('../../assets/images/informativeSign/vechileHeightLimit.png') },
    { key: 'vechileLimitLength', label: 'Vehicle Limit Length', labelNp: 'सवारी लम्बाई सीमा', src: require('../../assets/images/informativeSign/vechileLimitLength.png') },
    { key: 'vechileWeightLimit', label: 'Vehicle Weight Limit', labelNp: 'सवारी तौल सीमा', src: require('../../assets/images/informativeSign/vechileWeightLimit.png') },
    { key: 'vechileWidthLimit', label: 'Vehicle Width Limit', labelNp: 'सवारी चौडाइ सीमा', src: require('../../assets/images/informativeSign/vechileWidthLimit.png') },
    { key: 'vechileMayComeLefttSide', label: 'Vehicle May Come Left Side', labelNp: 'बायाँतर्फबाट सवारी आउन सक्ने', src: require('../../assets/images/informativeSign/vechileMayComeLefttSide.png') },
    { key: 'vechileMayComeRightSide', label: 'Vehicle May Come Right Side', labelNp: 'दायाँतर्फबाट सवारी आउन सक्ने', src: require('../../assets/images/informativeSign/vechileMayComeRightSide.png') },
    { key: 'noEntry', label: 'No Entry', labelNp: 'प्रवेश निषेध', src: require('../../assets/images/informativeSign/noEntry.png') },
  ];

export const restrictiveSign: { key: string; label: string; labelNp: string; src: any }[] = [
  { key: 'noHorn', label: 'No Horn', labelNp: 'हर्न बजाउन निषेध', src: require('../../assets/images/restrictiveSign/noHorn.png') },
  { key: 'noLeftTurn', label: 'No Left Turn', labelNp: 'बायाँ मोड्न निषेध', src: require('../../assets/images/restrictiveSign/noLeftTurn.png') },
  { key: 'noOvertake', label: 'No Overtake', labelNp: 'ओभरटेक गर्न निषेध', src: require('../../assets/images/restrictiveSign/noOvertake.png') },
  { key: 'noOxenCart', label: 'No Oxen Cart', labelNp: 'गाडा / गोरुगाडा निषेध', src: require('../../assets/images/restrictiveSign/noOxenCart.png') },
  { key: 'noParking', label: 'No Parking', labelNp: 'पार्किङ निषेध', src: require('../../assets/images/restrictiveSign/noParking.png') },
  { key: 'noRightTurn', label: 'No Right Turn', labelNp: 'दायाँ मोड्न निषेध', src: require('../../assets/images/restrictiveSign/noRightTurn.png') },
  { key: 'noStoppage', label: 'No Stoppage', labelNp: 'सवारी रोक्न निषेध', src: require('../../assets/images/restrictiveSign/noStoppage.png') },
  { key: 'noTruck', label: 'No Truck', labelNp: 'ट्रक प्रवेश निषेध', src: require('../../assets/images/restrictiveSign/noTruck.png') },
  { key: 'noUturn', label: 'No U Turn', labelNp: 'यु-टर्न निषेध', src: require('../../assets/images/restrictiveSign/noUturn.png') },
  { key: 'speedLimitEnd', label: 'Speed Limit End', labelNp: 'गति सीमा समाप्त', src: require('../../assets/images/restrictiveSign/speedLimitEnd.png') },
  { key: 'turnRight', label: 'Turn Right', labelNp: 'दायाँ मोड्नुहोस्', src: require('../../assets/images/restrictiveSign/turnRight.png') },
];

export const numberSign: { key: string; label: string; labelNp: string; src: any }[] = [
  { key: '2', label: '2', labelNp: '२', src: require('../../assets/images/eyeTestImg/2.png') },
  { key: '3', label: '3', labelNp: '३', src: require('../../assets/images/eyeTestImg/3.png') },
  { key: '5', label: '5', labelNp: '५', src: require('../../assets/images/eyeTestImg/5.png') },
  { key: '6', label: '6', labelNp: '६', src: require('../../assets/images/eyeTestImg/6.png') },
  { key: '7', label: '7', labelNp: '७', src: require('../../assets/images/eyeTestImg/7.png') },
  { key: '8', label: '8', labelNp: '८', src: require('../../assets/images/eyeTestImg/8.png') },
  { key: '9', label: '9', labelNp: '९', src: require('../../assets/images/eyeTestImg/9.png') },
  { key: '12', label: '12', labelNp: '१२', src: require('../../assets/images/eyeTestImg/12.png') },
  { key: '15', label: '15', labelNp: '१५', src: require('../../assets/images/eyeTestImg/15.png') },
  { key: '16', label: '16', labelNp: '१६', src: require('../../assets/images/eyeTestImg/16.png') },
  { key: '26', label: '26', labelNp: '२६', src: require('../../assets/images/eyeTestImg/26.png') },
  { key: '27', label: '27', labelNp: '२७', src: require('../../assets/images/eyeTestImg/27.png') },
  { key: '29', label: '29', labelNp: '२९', src: require('../../assets/images/eyeTestImg/29.png') },
  { key: '35', label: '35', labelNp: '३५', src: require('../../assets/images/eyeTestImg/35.png') },
  { key: '42', label: '42', labelNp: '४२', src: require('../../assets/images/eyeTestImg/42.png') },
  { key: '45', label: '45', labelNp: '४५', src: require('../../assets/images/eyeTestImg/45.png') },
  { key: '73', label: '73', labelNp: '७३', src: require('../../assets/images/eyeTestImg/73.png') },
  { key: '74', label: '74', labelNp: '७४', src: require('../../assets/images/eyeTestImg/74.png') },
  { key: '96', label: '96', labelNp: '९६', src: require('../../assets/images/eyeTestImg/96.png') },
  { key: '97', label: '97', labelNp: '९७', src: require('../../assets/images/eyeTestImg/97.png') },
];

export default function PracticeMoreConstantRoute() {
  return null;
}