export type KnowledgeQuestion = {
  question: string;
  options: [string, string, string, string];
};

// NOTE: Correct answers are not marked in the source provided.
// The exam screen will TEMPORARILY assume the first option is correct
// until an official answer key is supplied.
export const knowledgeQuestions: KnowledgeQuestion[] = [
  { question: 'Who should first be prioritized on Zebra Crossing?', options: ['(a) Male', '(b) Female', '(c) Cattle', '(d) Pedestrian'] },
  { question: 'How would one know the speed of the vehicle ahead getting slow?', options: ['(a) By brake Light.', "(b) Through the driver’s gestures", '(c) If the smoke of the silencer is getting less', '(d) None of them'] },
  { question: 'Whom should be prioritized while crossing the road?', options: ['(a) School students', '(b) Physically disabled', '(c) Senior Citizen', '(d) All of the above'] },
  { question: 'Which vehicle should be given priority while driving on road?', options: ['(a) Hearse Van.', '(b) Fire brigade', '(c) Ambulance', '(d) All of the above'] },
  { question: 'What should be done to overtake the vehicle moving ahead?', options: ['(a) By turning on headlight', '(b) By blowing horn', '(c) By turning on side light', '(d) All of the above'] },
  { question: 'On which side of the road do people drive their vehicle in Nepal?', options: ['(a) Right side', '(b) Left side', '(c) whatever side available', '(d) None of the above'] },
  { question: 'In which speed is the consumption of fuel low?', options: ['(a) Slow speed', '(b) Medium speed', '(c) High speed', '(d) Both slow and medium speed'] },
  { question: 'What would you do when you see an ambulance is following your vehicle?', options: ['(a) Stop your vehicle', '(b) Give side, let it go', '(c) Increase speed', '(d) Overtake it'] },
  { question: 'In what kind of road is most dangerous if the brake fails?', options: ['(a) Road going uphill', '(b) Road going downhill', '(c) Flat road', '(d) Gravel road'] },
  { question: 'In which speed is the consumption of fuel high?', options: ['(a) Slow Speed', '(b) Medium Speed', '(c) High speed', '(d) All of the above'] },
  { question: 'Which vehicle either going up or down, should give side?', options: ['(a) Moving upward.', '(b) Moving downward.', '(c) Both of them', '(d) None of them'] },
  { question: 'Which vehicle either going straight or turning round should be prioritized?', options: ['(a) Vehicle turning round', '(b) Vehicle going straghit', '(c) Both of them', '(d) None of them'] },
  { question: 'Why should one keep on changing gear?', options: ['(a) To decrease speed', '(b) To increase speed', '(c) To blow horn', '(d) Both to increase or to decrease speed'] },
  { question: 'Which side should be used for driving low speed vehicle slowly in Nepal?', options: ['(a) From middle', '(b) From right', '(c) From left', '(d) Whatever side one prefers'] },
  { question: 'Which part in a four wheeler do the feet control?', options: ['(a) Clutch', '(b) Brake', '(c) Accelerator', '(d) All of the above'] },
  { question: 'Which vehicle either moving upwards or moving downwards should be prioritized?', options: ['(a) Vehicle moving downward', '(b) Vehicle moving upward', "(c) Side shoudn’t be given", '(d) Whosoever can, should go ahead'] },
  { question: 'Which vehicle doesn`t move on road?', options: ['(a) Ship', '(b) plane', '(c) Helicopter', '(d) All of the above'] },
  { question: 'What should a driver do to know whether the speed of the vehicle ahead is low or high?', options: ['(a) By asking the driver', '(b) From the gestures of the driver', '(c) Guessing', '(d) None of these.'] },
  { question: 'What does the oil pressure indicator show in vehicle?', options: ['(a) Diesel', '(b) Mobil', '(c) Water', '(d) Petrol'] },
  { question: 'When should the seat belt be used?', options: ['(a) Those who sit at the front', '(b) As soon as the police see', '(c) while moving down', '(d) While moving up'] },
  { question: 'Which vehicle should not be prioritized first while driving?', options: ['(a) Car', '(b) Motorcycle', '(c) Truck', '(d) All of the above'] },
  { question: 'What should be done to allow vehicle coming from rear side to move ahead?', options: ['(a) By gesturing from hand', '(b) By turning on side light', '(c) Both A & B', '(d) None of them'] },
  { question: 'In Nepal driving on which side is punishable?', options: ['(a) Right side', '(b) Left side', '(c) Both', '(d) None of them'] },
  { question: 'What is the main function of left hand in four wheelers?', options: ['(a) To Brake', '(b) To control handle', '(c) To use hand brake', '(d) All of the above'] },
  { question: 'What should you do when you see a fire brigade coming behind you?', options: ['(a) Stop the vehicle', '(b) Give side', '(c) Increase Speed', '(d) Ignore'] },
  { question: 'What should one do while turning the vehicle?', options: ['(a) Turn the side light', '(b) Lower the speed', '(c) Look both sides', '(d) All of the above'] },
  { question: 'What kind of vehicle should be prioritized?', options: ['(a) Vehicle moving downward', '(b) Vehicle moving upward', '(c) Both of them', '(d) Non of them'] },
  { question: 'What should one do either to lower or increase the speed?', options: ['(a) Change gear', '(b) Press or release accelerator', '(c) Both of them', '(d) None of them'] },
  { question: 'Which lane of the road should be used while driving vehicle at higher speed?', options: ['(a) Middle Lane', '(b) Side Lane', '(c) Both of them', '(d) None of them'] },
  { question: 'In general, when should one turn on the headlight?', options: ['(a) Day Time', '(b) Dark/Night Time', '(c) On seeing traffic police', '(d) On having accident'] },
  { question: 'What do we understand by temporary route permit?', options: ['(a) To drive on the permitted road only', '(b) To get permission to drive on the road which is not stated on the regular permit', '(c) To get permission to drive along the local road', '(d) To drive time and again'] },
  { question: 'What shouldn`t be done before you get driving license?', options: ['(a) Not to drive the vehicle', '(b) Not to sit in the vehicle', '(c) Not to buy vehicle', '(d) None of the above'] },
  { question: 'What should one do to his or her vehicle while the VIP vehicle is on the road?', options: ['(a) To stop and give way', '(b) To blow horn', '(c) To drive vehicle', '(d) All of the above'] },
  { question: 'How should one behave to the traffic police when she or he stops the vehicle showing your fault?', options: ["(a) To insist that you haven`t done anything wrong", '(b) To run away from the traffic police.', '(c) To realize your mistake politely.', "(d) To make other drivers your withness insisting that you haven’t done anything wrong"] },
  { question: 'How much fuel should be better to put in the vehicle?', options: ['(a) Only a little', '(b) Half Tank', '(c) Fill the tank if fuel is finished.', '(d) Full tank if possible'] },
  { question: 'What kind of vehicle isn`t allowed for use in public transportation?', options: ['(a) Private vehicle', '(b) Public vehicle', '(c) Tourist vehicle', '(d) All of the above'] },
  { question: 'What do you mean by conductor/steward/attendant?', options: ['(a) One who drives', '(b) One who has got license to drive', '(c) One who assists in vehicle', '(d) All of the above'] },
  { question: 'What kind of vehicle has L sign?', options: ['(a) Government vehicle', '(b) Learner`s vehicle', '(c) Diplomatic vehicle', '(d) Public vehicle'] },
  { question: 'How would one signal while overtaking the vehicle ahead?', options: ['(a) Requesting him/her to stop by phone', '(b) Gesturing with hand', '(c) Blowing Horn', '(d) None of the above'] },
  { question: 'For what purpose should the looking glass be used?', options: ['(a) To overtake', '(b) To back', '(c) Both of them', '(d) Not of them'] },
  { question: 'What quality should a driver have?', options: ['(a) Patience', '(b) Sweet speaking', '(c) Friendly', '(d) All of the above'] },
  { question: 'What should be done for safe jounery?', options: ['(a) Follow the traffic rules', '(b) Drive randomly', '(c) Drive speedly', '(d) All of the above'] },
  { question: 'What should be done while driving if anything is not visible during rain?', options: ['(a) Switch wiper', '(b) Speed up', '(c) Stop the vehicle', '(d) Blow horn'] },
  { question: 'In which gear should the vehicle be parked on sloped road?', options: ['(a) No 1 gear', '(b) No 3 grar', '(c) Back gear', '(d) No 5 gear.'] },
  { question: 'Among the following options, which one isn’t in electric vehicle?', options: ['(a) Silencer pipe', '(b) Accelerator', '(c) Clutch', '(d) Gear'] },
  { question: 'What kind of vehicle is it when it has Ba 1 ba number plate?', options: ['(a) Private motorcycle', '(b) Government motorcycle', "(c) Corportation's motorcycle", '(d) Rental motorcycle'] },
  { question: 'Among the offices mentioned below, in which office should one pay vehicular tax?', options: ['(a) Intenal Revenue Office', '(b) Custom Office', '(c) Transport Management Office', '(d) Excise Duty Office'] },
  { question: 'What should be done if embossed number plate doesn`t work?', options: ['(a) To change it as one likes', '(b) To change after submitting an application at Transport Management Office', '(c) To change after repairing', '(d) All of the above'] },
  { question: 'What kind of vehicle is it if it has ma 1 ng?', options: ['(a) Private car', '(b) Taxi', '(c) Tempoo', "(d) Corporation`s jeep"] },
  { question: 'What is it called if the vehicle is registered in two or more than two person’s name?', options: ['(a) Vehicle registration', '(b) Joint vehicle registration', '(c) Vehicle buying or selling', '(d) Vehicle ownership'] },
  { question: 'What is the colour of Bluebook?', options: ['(a) Black', '(b) Red', '(c) Blue', '(d) Yello.'] },
  { question: 'Which are the emergency vehicles?', options: ['(a) Fire brigade', '(b) Ambulance', '(c) Hearse van', '(d) All of the above'] },
  { question: 'Which vehicle is used to douse the fire?', options: ['(a) Fire brigade', '(b) Ambulance', '(c) Hearse van', '(d) Taxi'] },
  { question: 'In ability to differentiate which of the following color disqualifies a person from getting driving license?', options: ['(a) Red.', '(b) White.', '(c) Black.', '(d) Blue.'] },
  { question: 'What is embossed number plate?', options: ['(a) Number plate written with Enamel', '(b) Number plate written with etched/ brocaded /carved letter', '(c) Number plate written with raised letters', '(d) All of the above'] },
  { question: 'What is First Aid?', options: ['(a) Taking the patient to hospital immediately.', '(b) Bandaging in ordinary injuries', "(c) Calling the docter if he/she isn`t present", '(d) All of the above'] },
  { question: 'Which vehicle is registered in the largest number in Nepal?', options: ['(a) Car', '(b) Bus', '(c) Motercycle', '(d) E-rickshaw'] },
  { question: 'Among the given vehicles, which one should not be registered?', options: ['(a) Electric cycle', '(b) Electric cycle with pedal', '(c) Electric scooter', '(d) Electric motorcycle'] },
  { question: 'What happens if one changes the colour of vehicle with his/her own desire?', options: ['(a) Looks good', '(b) Looks clean', '(c) Grows Expenses', '(d) Deserves fine'] },
  { question: 'Which vehicle is used to carry patients/sick people to hospital?', options: ['(a) Fire brigade', '(b) Ambulance', '(c) Hearse van', '(d) Taxi'] },
  { question: 'What does a vehicle with a green number plate indicate?', options: ['(a) Private Vehicle', '(b) Government vehicle', '(c) Corporate vehicle', '(d) Tourist vehicle'] },
  { question: 'Why is driving license necessary?', options: ['(a) To drive vehicle', '(b) To buy vehicle', '(c) To sell vehicle', '(d) None of them.'] },
  { question: 'What is vehicle registration certificate\\blue book?', options: ['(a) Certificate with complete description of vehicle.', '(b) License to drive vehicle', '(c) Certificate with permission to drive vehicle', '(d) None of them'] },
  { question: 'Which vehicle has black number plate?', options: ['(a) Government vehicle', '(b) Public vehicle', '(c) Corporation vehicle', '(d) Tourist vehicle'] },
  { question: 'With what documents should one submit application to the office if the driving license is lost?', options: ['(a) Application and fee with traffic police recomendation letter', '(b) Recommendation from municipal ward office', '(c) Recommendation letter from District Administration Office', '(d) All of the above'] },
  { question: 'Among the following options, which condition is considered as disqualification to get the driving license?', options: ['(a) Visual impairment', '(b) Night blindness', '(c) Having weak legs & hands', '(d) All of the above'] },
  { question: 'Which office doesn`t work for the renewal of license?', options: ['(a) Traffice Police Office', '(b) Vehicle Fitness Test Center', '(c) Department of Transport Management', '(d) All of the above'] },
  { question: 'Which office issues the license certificate before permitting the public vehicle to move on road?', options: ['(a) District Administration Office.', '(b) Traffice Police Office.', '(c) Transport Management Office', '(d) All of the above'] },
  { question: 'Which vehicle isn`t allowed to operate without route permit?', options: ['(a) Private vehicle', '(b) Government Vehicle', '(c) Public vehicle', '(d) Diplomatic vehicle'] },
  { question: 'Which office has the right to change the permissible speed limit confirmed for vehicle?', options: ['(a) Traffice Police Office', '(b) Transport Management Office', '(c) Department of Transport Management', '(d) All of the above'] },
  { question: 'What should be done before driving out of order vehicle?', options: ['(a) Repair.', '(b) Fillup engine.', '(c) Nothing to be done.', '(d) Show the police.'] },
  { question: 'Who is the chairperson of Transportation Management Committee?', options: ['(a) Chief of Transport Management Office', '(b) District Police Chief', '(c) Chief of Traffic Police Office', '(d) Non of them'] },
  { question: 'How should one drive the vehicle along the three- lane road?', options: ['(a) From both sides', '(b) From three sides', '(c) From one side', '(d) None of them'] },
  { question: 'How would you start your four wheelers?', options: ['(a) By checking gear', '(b) By jamming on brake', '(c) By checking oil', '(d) By checking engine'] },
  { question: 'Which vehicle either small or big should give the side first?', options: ['(a) The vehicle coming straightly', '(b) Small vehicle', '(c) Big vehicle', '(d) All of the above'] },
  { question: 'Why should one change gear?', options: ['(a) Increase speed', '(b) Decrease speed', '(c) Blow horn', '(d) Both a & b'] },
  { question: 'In what condition can one not get the copy of driving license?', options: ['(a) Having lost the license', '(b) Having torn', '(c) Having old & torn', '(d) Having the orginal with him/herself'] },
  { question: 'Which signal should one give while moving ahead after starting vehicle?', options: ['(a) By turning on headlight', '(b) By turning on right side light', '(c) By turning on left side light', '(d) By turning on emergency light'] },
  { question: 'In which place should one lower the speed of vehicle?', options: ['(a) School area', '(b) Cross roads', '(c) Densely populated area', '(d) All of them'] },
  { question: 'Which one isn’t among the heavy equipment?', options: ['(a) Dozer', '(b) Mini bus', '(c) Loader', '(d) Mobile crane'] },
  { question: 'When was the first vehicle brought in Nepal?', options: ['(a) B.S. 1996', '(b) B.S. 2021', '(c) B.S. 2000', '(d) B.S. 2049'] },
  { question: 'What is the colour of foglight?', options: ['(a) Red', '(b) Yellow', '(c) Green', '(d) Blue'] },
  { question: 'Why is the spelling of ambulance written as mirror image format?', options: ['(a) So that it could be read rightly from the looking glass of the vehicle ahead', '(b) As it is the convention', '(c) To show the difference from others', '(d) None of the above'] },
  { question: 'What does the blue number plate in a vehicle indicate?', options: ['(a) Diplomatic vehicle', '(b) Government vehicle', '(c) Private vehicle', '(d) vehicle of Corporation'] },
  { question: 'Which certificate is first needed to a Nepali citizen to obtain driving license?', options: ['(a) Certificate given by driving school', '(b) Health Certificate', '(c) Nepali citizen certificate', '(d) Educational qualification certificate'] },
  { question: 'What is the process followed to re-register a vehicle in another Transport Management Office?', options: ['(a) Transfer registration', '(b) Renewal.', '(c) Re-registration.', '(d) Inter-zonal registration'] },
  { question: 'Whose duty is it to operate the exam of driving license dignified?', options: ['(a) Transport Management Office', '(b) Examinees', '(c) Traffice Police`s', '(d) All of the above'] },
  { question: 'What time is known as peak hour?', options: ['(a) Morning time.', '(b) Evening time.', '(c) One hour before and after the office opens and closes', '(d) Breakfast/Lunch hour'] },
  { question: 'For which vehicle third party insurance is mandatory?', options: ['(a) Rental bus, truck', '(b) Motorcycle', '(c) Private Car', '(d) All of the above'] },
  { question: 'Who is the chairperson of driving license examination committee?', options: ['(a) Chief of Transport Management Office', '(b) Chief of Department of Transport Management', '(c) Chief of Traffic Police Office', '(d) Chief of Driving School'] },
  { question: 'What do you mean by third party insurance?', options: ['(a) Passenger’s insurance', '(b) Padestrain’s insurance.', "(c) Vehicle's Insurance", "(d) Driver's insurance"] },
  { question: 'Which office’s vehicle has yellow number plate?', options: ['(a) Government vehicle.', '(b) Private vehicle.', '(c) Public vehicle.', '(d) Corporation vehicle.'] },
  { question: 'From which side one should alight after the vehicle stops?', options: ['(a) Left side.', '(b) Right side.', '(c) Back side.', '(d) Front side.'] },
  { question: 'In what condition can one obtain the duplicate copy of driving license?', options: ['(a) Having lost.', '(b) Having torn.', '(c) Having stolen.', '(d) All of the above'] },
  { question: 'What would you do when you find someone’s driving license?', options: ['(a) Tearing and throwing', '(b) Bring it to home.', '(c) Submit it to the traffic police.', '(d) Ignore it.'] },
  { question: 'Which vehicle doesn`t need route permit?', options: ['(a) Motorcycle.', '(b) Public truck.', '(c) Public jeep.', '(d) Public bus.'] },
  { question: 'Which office is primarily responsible to manage movement of vehicles?', options: ['(a) District Administration Office.', '(b) Transport Management Office', '(c) District Police Office', '(d) Traffic Police Office.'] },
  { question: 'What educational qualification is needed for driving license?', options: ['(a) SLC/SEE', '(b) Plus 2 or equivalent.', '(c) Higher Education.', '(d) Literate'] },
  { question: 'When was Department of Transport established?', options: ['(a) V.S. 2051', '(b) V.S. 2041', '(c) V.S. 2052', '(d) V.S. 2049'] },
  { question: 'What is given more consideration while driving during rain?', options: ['(a) Brake', '(b) Skidding', '(c) Caution to spread mud', '(d) All of the above'] },
  { question: 'What kind of vehicle’s ownership shouldn’t be transfered?', options: ['(a) Those which crossed 20 years by production year.', '(b) Those which crossed 15 years by production year.', '(c) Those which crossed 5 years by production year.', '(d) Those which crossed 25 years by production year.'] },
  { question: 'What should be done if the auctioned vehicle is to be auctioned once again?', options: ['(a) Auctioned again.', '(b) Use it without registration.', '(c) Scrapped as per the law.', '(d) Register for auction as per the rule.'] },
  { question: 'After how many hours should a long route public vehicle take a break?', options: ['(a) Every three hours.', '(b) Every four hours.', '(c) Every two hours', '(d) Every One hour'] },
  { question: 'Which office renews the driving license?', options: ['(a) Transportation Management office.', '(b) Department of Transport Management', '(c) Vehicle Fitness Test Center', '(d) Traffic Police Office.'] },
  { question: 'On what kind of road should we not drive the public vehicle?', options: ['(a) Not pitched.', '(b) Gravel road.', '(c) Route not allowed.', '(d) Hilly road.'] },
  { question: 'What kind of vehicle wouldn’t have the provision of vehicular tax?', options: ['(a) Government vehicle.', '(b) Corporation vehicle', '(c) Diplomatic vehicle.', '(d) Applies to all'] },
  { question: 'What would you do if engine block of vehicle breaks?', options: ['(a) To get it changed at workshop.', '(b) To get it changed after you get permission from Transportation Management Office.', "(c) To insert old vehicle’s engine block", '(d) To get it changed at market immediately when it breaks.'] },
  { question: 'What is it called to transform foreign driving license into Nepal?', options: ['(a) Internationalization.', '(b) Foreignization.', '(c) Transforming into Nepali (Nepalization).', '(d) Nationalization'] },
  { question: 'What kind of test/trial examination should be taken to transform foregin driving license into Nepali?', options: ['(a) Written.', '(b) Oral.', '(c) practical.', '(d) None of them.'] },
  { question: 'What provision is in Nepal about international/ foreign driving license?', options: ['(a) Remain invalid instantly.', '(b) Permission to drive accross Nepal.', '(c) Permission to drive only in Kathmandu valley.', '(d) None of them.'] },
  { question: "What kind of driving license’s record/data is deleted?", options: ['(a) If not renewed till five years after renewal time is finished.', '(b) Having old license.', '(c) The driving license of those who had done accident.', '(d) All of the above'] },
  { question: 'When should one go to the office for biometrics after filling the application form for driving licence?', options: ['(a) Next day.', '(b) Within one year.', '(c) Within three monts.', '(d) Visit date given by the system.'] },
  { question: 'Which type of road is upto 25 KM long?', options: ['(a) Long road.', '(b) Short road.', '(c) Local road.', '(d) Midium size road.'] },
  { question: 'Among the given vehicles, which one shoudn’t take the route permit?', options: ['(a) Ambulance.', '(b) Fire brigade.', '(c) Motorcycle.', '(d) All of the above'] },
  { question: 'For what kind of vehicle can the authorized officer renew for upto five years?', options: ['(a) Government.', '(b) Corporation & diplomatic', '(c) Private', '(d) All of the above'] },
  { question: 'What kind of vehicle is fire brigade?', options: ['(a) Passenger carrier', '(b) Goods carriers', '(c) Hearse Van.', '(d) Fire controller.'] },
  { question: 'What happens if one keeps on pressing on the accelerator?', options: ['(a) Vehicle doesn`t work.', '(b) Traffic police charges fine.', '(c) Vehicle speeds up.', '(d) All of the above'] },
  { question: 'Which entity do the transportation management offices come under?', options: ['(a) Department of Transport Management', '(b) Provincial Ministry for Physical Infrastructure Development', '(c) Ministry for Physical Infrastructure & Transportation', '(d) None of the above'] },
  { question: 'In what condition do the vehicles maintain wide distance between each other while driving?', options: ['(a) During the time of visit of distinguished personalities.', '(b) During sunshine', "(c) When its not raining", '(d) During foggy/misty time'] },
  { question: 'What shouldn’t be done while driving?', options: ['(a) To talk on mobile', '(b) To use alcoholic drink', '(c) To overtake randomly', '(d) All of the above'] },
  { question: 'How should we cross the road?', options: ['(a) Stopping while walking', '(b) Running', '(c) Slowly through zebra crossing', '(d) Walking smoothly'] },
  { question: 'Among the options given below, which one is the duty of the driver?', options: ['(a) To collect travelling fare', '(b) To drive vehicle after checking the condition.', '(c) To clean the road', '(d) All of the above'] },
  { question: 'What should be done while driving in the urban area?', options: ['(a) Limit the speed.', '(b) Increase the speed.', '(d) Stop the vehicle.', '(d) None of them'] },
  { question: 'What is mandatory while driving?', options: ['(a) To use seat belt', '(b) To put on glasses', '(c) To put on jacket.', '(d) All of the above'] },
  { question: 'What do you understand by vehicle safely?', options: ['(a) To park on the road', '(b) To stop the vehicle at neutral gear.', '(c) To lock the vehicle.', '(d) To park the vehicle on downward road.'] },
  { question: 'How would the vehicle`s brake fail?', options: ['(a) When the brake heats', '(b) When the brake pipe breaks.', '(c) When there is no brake oil.', '(d) All of the above'] },
  { question: 'What happens to those who blow the pressure horns?', options: ['(a) Inprisonment', '(b) Fine.', '(c) Confiscation of the vehicle.', '(d) Nothing happens'] },
  { question: 'What do the marks in the middle of road indicate?', options: ['(a) Not to race.', '(b) To divide the road lane.', '(c) Not to cross the road.', '(d) Not to overtake.'] },
  { question: 'Where should the bluebook be kept?', options: ['(a) At home.', '(b) With drivers', '(c) At office.', '(d) All of the above'] },
  { question: 'When are the side lights turned on?', options: ['(a) While changing lane.', '(b) While overtaking.', '(c) While parking the vehicle.', '(d) Both a & b'] },
];


// Correct answer key for the first 130 questions (letters a-d). Remaining questions default to 'a'.
export const knowledgeAnswerKeyLetters: ('a'|'b'|'c'|'d')[] = [
  'd','a','d','d','d','b','b','b','b','c',
  'b','b','d','c','d','b','d','d','b','a',
  'd','c','a','b','b','d','b','c','a','b',
  'b','a','a','c','d','a','c','b','c','c',
  'd','a','a','a','a','d','c','b','c','b',
  'c','d','a','a','c','d','c','b','d','b',
  'd','a','a','b','a','d','a','c','c','c',
  'a','a','c','a','c','d','d','d','d','b',
  'a','b','a','a','c','a','d','c','d','a',
  'b','c','a','d','c','a','d','d','b','d',
  'a','c','d','b','a','d','c','b','d','a',
  'd','c','a','a','c','d','b','b','b','d'
];


